### ISSUE TITLE
Use `wpcf7_submit` instead of `wpcf7_before_send_mail`?

### ISSUE THREAD

**Issue by remcotolsma** [wp-pay-extensions/contact-form-7#5]
I'm working on the review of the following pull request:

- https://github.com/pronamic/wp-pronamic-pay-contact-form-7/pull/4

I use `wp-env` for testing and don't have a mail solution active. That's why I disabled the mail for Contact Form 7:

```
skip_mail: on
```

<img width="608" alt="Scherm­afbeelding 2023-02-21 om 10 19 32" src="https://user-images.githubusercontent.com/869674/220302268-e252420d-db9a-47a7-bb61-ab21c55e047b.png">

Payments are not working when users do this?

https://github.com/pronamic/wp-pronamic-pay-contact-form-7/blob/3877d0dfcfa618b42352136f2c4e39570299834b/src/Extension.php#L98

Should we use the `wpcf7_submit` action just like in Flamingo?

https://github.com/takayukister/contact-form-7/blob/6efa44cf62c055bbeb316290b66f405d4bf01946/modules/flamingo.php#L7

- https://github.com/takayukister/contact-form-7
- https://github.com/takayukister/flamingo

**Comment by remcotolsma** [comment]
> ⚠️ As the `wpcf7_submit` action is called after the email has been sent, sending emails will no longer be aborted if the payment could not be started at the gateway.

This does not work well with mail tags. Since the official Stripe integration also uses `wpcf7_before_send_mail`. We might should use a combination of `wpcf7_before_send_mail` and `wpcf7_submit`.

https://github.com/takayukister/contact-form-7/blob/6efa44cf62c055bbeb316290b66f405d4bf01946/modules/stripe/stripe.php#L133-L194

**Comment by rvdsteege** [comment]
> Payments are not working when users do this?

They do 🎉

The `wpcf7_before_send_mail` is called once the form validated, but doesn't necessarily mean that a mail will be send. This filter also gives us the opportunity to _abort_ sending any mails (e.g. when the payment could not be created at the gateway). Also, as mentioned, we need to use the `wpcf7_before_send_mail` action because of mail tags (the `wpcf7_submit` action is too late for that). The `skip_mail: on` configuration is only used right before sending the mail in `mail()`.

- https://github.com/takayukister/contact-form-7/blob/6efa44cf62c055bbeb316290b66f405d4bf01946/includes/submission.php#L102-L126
- https://github.com/takayukister/contact-form-7/blob/6efa44cf62c055bbeb316290b66f405d4bf01946/includes/submission.php#L782-L794C4
